CREATE TABLE `short_url` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `origin_url` VARCHAR(255) NOT NULL,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT = 20000;
