name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update submodules to latest commit on main branch
      run: git submodule update --remote
    
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # gradle caching - 빌드 시간 향상
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Build with Gradle Wrapper
      run: ./gradlew build
        
    - name: Build Docker Image For Spring
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener .
        docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener

    - name: Deploy and Start Spring Boot Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/url-shortener
          sudo docker stop server || true
          sudo docker run -d -p 8080:8080 --name server ${{ secrets.DOCKER_USERNAME }}/url-shortener
          docker image prune -f

    - name: Deploy Spring Boot Application
      run: |
        nohup java -jar /path/to/your/application.jar > stdout.log 2> stderr.log &
    
    - name: Retrieve logs
      run: |
        ssh ec2-user@${{ secrets.HOST_PROD }} 'echo "STDOUT:" && sudo tail -n 100 /var/log/docker.log && echo "STDERR:" && sudo tail -n 100 /var/log/docker.err'
